apiVersion: v1
kind: Service
metadata:
  name: headtotails
  namespace: headscale
  labels:
    app.kubernetes.io/name: headtotails
    app.kubernetes.io/component: api-proxy
spec:
  selector:
    app.kubernetes.io/name: headtotails
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  type: ClusterIP
