package api

import (
	"fmt"
	"strings"
)

//go:generate go run ../../cmd/gen-metrics-docs

// RenderMetricsMarkdown renders docs/metrics.md from metric definitions.
func RenderMetricsMarkdown() string {
	var b strings.Builder

	b.WriteString("# Metrics\n\n")
	b.WriteString("<!-- Code generated by `go generate ./...`; DO NOT EDIT. -->\n\n")
	b.WriteString("This document is generated from `internal/api/metrics_catalog.go`.\n")
	b.WriteString("Custom metrics are exposed on the Prometheus scrape endpoint: `/metrics`.\n\n")

	b.WriteString("## Supported Custom Metrics\n\n")
	b.WriteString("| Name | Type | Labels | Help |\n")
	b.WriteString("|---|---|---|---|\n")
	for _, metric := range CustomMetricDocs() {
		labels := "-"
		if len(metric.Labels) > 0 {
			labels = strings.Join(metric.Labels, ", ")
		}
		_, _ = fmt.Fprintf(&b, "| `%s` | `%s` | `%s` | %s |\n",
			metric.Name,
			metric.Type,
			labels,
			metric.Help,
		)
	}
	b.WriteString("\n")

	b.WriteString("## Metric Notes\n\n")
	for _, metric := range CustomMetricDocs() {
		_, _ = fmt.Fprintf(&b, "- `%s`: %s\n", metric.Name, metric.Notes)
	}
	b.WriteString("\n")

	b.WriteString("## Production Monitoring Gaps\n\n")
	b.WriteString("The current implementation provides request totals/latency and upstream gRPC error counts.\n")
	b.WriteString("For stronger production monitoring, add:\n\n")
	b.WriteString("- `headtotails_http_inflight_requests` gauge for saturation and concurrency.\n")
	b.WriteString("- `headtotails_headscale_rpc_duration_seconds` histogram by gRPC method/code.\n")
	b.WriteString("- `headtotails_headscale_rpc_requests_total` counter by gRPC method/code.\n")
	b.WriteString("- `headtotails_oauth_token_requests_total` counter by result (`success`, `invalid_client`, `invalid_grant`).\n")
	b.WriteString("- Optional request/response size histograms for payload growth and cost visibility.\n\n")

	b.WriteString("## Starter Alerting and SLO Signals\n\n")
	b.WriteString("- Error rate: `sum(rate(headtotails_requests_total{status=~\"5..\"}[5m])) / sum(rate(headtotails_requests_total[5m]))`\n")
	b.WriteString("- Latency p95: `histogram_quantile(0.95, sum by (le) (rate(headtotails_request_duration_seconds_bucket[5m])))`\n")
	b.WriteString("- Upstream failures: `sum(rate(headtotails_grpc_errors_total[5m])) by (grpc_code)`\n")

	return b.String()
}
