// Code generated by mockery v2. DO NOT EDIT.
// Run `make generate` to regenerate.

package headscale

import (
	"context"

	v1 "github.com/juanfont/headscale/gen/go/headscale/v1"
	"github.com/stretchr/testify/mock"
)

// MockHeadscaleClient is a mock implementation of HeadscaleClient.
type MockHeadscaleClient struct {
	mock.Mock
}

func (m *MockHeadscaleClient) ListNodes(ctx context.Context, user string) ([]*v1.Node, error) {
	args := m.Called(ctx, user)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]*v1.Node), args.Error(1)
}

func (m *MockHeadscaleClient) GetNode(ctx context.Context, id uint64) (*v1.Node, error) {
	args := m.Called(ctx, id)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*v1.Node), args.Error(1)
}

func (m *MockHeadscaleClient) DeleteNode(ctx context.Context, id uint64) error {
	args := m.Called(ctx, id)
	return args.Error(0)
}

func (m *MockHeadscaleClient) ExpireNode(ctx context.Context, id uint64) error {
	args := m.Called(ctx, id)
	return args.Error(0)
}

func (m *MockHeadscaleClient) RenameNode(ctx context.Context, id uint64, name string) (*v1.Node, error) {
	args := m.Called(ctx, id, name)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*v1.Node), args.Error(1)
}

func (m *MockHeadscaleClient) SetTags(ctx context.Context, id uint64, tags []string) (*v1.Node, error) {
	args := m.Called(ctx, id, tags)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*v1.Node), args.Error(1)
}

func (m *MockHeadscaleClient) SetApprovedRoutes(ctx context.Context, id uint64, routes []string) (*v1.Node, error) {
	args := m.Called(ctx, id, routes)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*v1.Node), args.Error(1)
}

func (m *MockHeadscaleClient) AuthApprove(ctx context.Context, user, nodeKey string) (*v1.Node, error) {
	args := m.Called(ctx, user, nodeKey)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*v1.Node), args.Error(1)
}

func (m *MockHeadscaleClient) ListPreAuthKeys(ctx context.Context) ([]*v1.PreAuthKey, error) {
	args := m.Called(ctx)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]*v1.PreAuthKey), args.Error(1)
}

func (m *MockHeadscaleClient) CreatePreAuthKey(ctx context.Context, req *v1.CreatePreAuthKeyRequest) (*v1.PreAuthKey, error) {
	args := m.Called(ctx, req)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*v1.PreAuthKey), args.Error(1)
}

func (m *MockHeadscaleClient) ExpirePreAuthKey(ctx context.Context, id uint64) error {
	args := m.Called(ctx, id)
	return args.Error(0)
}

func (m *MockHeadscaleClient) DeletePreAuthKey(ctx context.Context, id uint64) error {
	args := m.Called(ctx, id)
	return args.Error(0)
}

func (m *MockHeadscaleClient) ListUsers(ctx context.Context) ([]*v1.User, error) {
	args := m.Called(ctx)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]*v1.User), args.Error(1)
}

func (m *MockHeadscaleClient) DeleteUser(ctx context.Context, id uint64) error {
	args := m.Called(ctx, id)
	return args.Error(0)
}

func (m *MockHeadscaleClient) GetPolicy(ctx context.Context) (string, error) {
	args := m.Called(ctx)
	return args.String(0), args.Error(1)
}

func (m *MockHeadscaleClient) SetPolicy(ctx context.Context, policy string) error {
	args := m.Called(ctx, policy)
	return args.Error(0)
}
