// Code generated by mockery v2.53.6. DO NOT EDIT.

package headscale

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	v1 "github.com/juanfont/headscale/gen/go/headscale/v1"
)

// MockHeadscaleClient is an autogenerated mock type for the HeadscaleClient type
type MockHeadscaleClient struct {
	mock.Mock
}

// AuthApprove provides a mock function with given fields: ctx, user, nodeKey
func (_m *MockHeadscaleClient) AuthApprove(ctx context.Context, user string, nodeKey string) (*v1.Node, error) {
	ret := _m.Called(ctx, user, nodeKey)

	if len(ret) == 0 {
		panic("no return value specified for AuthApprove")
	}

	var r0 *v1.Node
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*v1.Node, error)); ok {
		return rf(ctx, user, nodeKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *v1.Node); ok {
		r0 = rf(ctx, user, nodeKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Node)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, user, nodeKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreatePreAuthKey provides a mock function with given fields: ctx, req
func (_m *MockHeadscaleClient) CreatePreAuthKey(ctx context.Context, req *v1.CreatePreAuthKeyRequest) (*v1.PreAuthKey, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreatePreAuthKey")
	}

	var r0 *v1.PreAuthKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.CreatePreAuthKeyRequest) (*v1.PreAuthKey, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.CreatePreAuthKeyRequest) *v1.PreAuthKey); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.PreAuthKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.CreatePreAuthKeyRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteNode provides a mock function with given fields: ctx, id
func (_m *MockHeadscaleClient) DeleteNode(ctx context.Context, id uint64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteNode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeletePreAuthKey provides a mock function with given fields: ctx, id
func (_m *MockHeadscaleClient) DeletePreAuthKey(ctx context.Context, id uint64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeletePreAuthKey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteUser provides a mock function with given fields: ctx, id
func (_m *MockHeadscaleClient) DeleteUser(ctx context.Context, id uint64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExpireNode provides a mock function with given fields: ctx, id
func (_m *MockHeadscaleClient) ExpireNode(ctx context.Context, id uint64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ExpireNode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExpirePreAuthKey provides a mock function with given fields: ctx, id
func (_m *MockHeadscaleClient) ExpirePreAuthKey(ctx context.Context, id uint64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ExpirePreAuthKey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetNode provides a mock function with given fields: ctx, id
func (_m *MockHeadscaleClient) GetNode(ctx context.Context, id uint64) (*v1.Node, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetNode")
	}

	var r0 *v1.Node
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (*v1.Node, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) *v1.Node); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Node)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPolicy provides a mock function with given fields: ctx
func (_m *MockHeadscaleClient) GetPolicy(ctx context.Context) (string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetPolicy")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListNodes provides a mock function with given fields: ctx, user
func (_m *MockHeadscaleClient) ListNodes(ctx context.Context, user string) ([]*v1.Node, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for ListNodes")
	}

	var r0 []*v1.Node
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*v1.Node, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*v1.Node); ok {
		r0 = rf(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*v1.Node)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListPreAuthKeys provides a mock function with given fields: ctx, user
func (_m *MockHeadscaleClient) ListPreAuthKeys(ctx context.Context, user string) ([]*v1.PreAuthKey, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for ListPreAuthKeys")
	}

	var r0 []*v1.PreAuthKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*v1.PreAuthKey, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*v1.PreAuthKey); ok {
		r0 = rf(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*v1.PreAuthKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListUsers provides a mock function with given fields: ctx
func (_m *MockHeadscaleClient) ListUsers(ctx context.Context) ([]*v1.User, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 []*v1.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*v1.User, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*v1.User); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*v1.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RenameNode provides a mock function with given fields: ctx, id, name
func (_m *MockHeadscaleClient) RenameNode(ctx context.Context, id uint64, name string) (*v1.Node, error) {
	ret := _m.Called(ctx, id, name)

	if len(ret) == 0 {
		panic("no return value specified for RenameNode")
	}

	var r0 *v1.Node
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, string) (*v1.Node, error)); ok {
		return rf(ctx, id, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, string) *v1.Node); ok {
		r0 = rf(ctx, id, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Node)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, string) error); ok {
		r1 = rf(ctx, id, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetApprovedRoutes provides a mock function with given fields: ctx, id, routes
func (_m *MockHeadscaleClient) SetApprovedRoutes(ctx context.Context, id uint64, routes []string) (*v1.Node, error) {
	ret := _m.Called(ctx, id, routes)

	if len(ret) == 0 {
		panic("no return value specified for SetApprovedRoutes")
	}

	var r0 *v1.Node
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, []string) (*v1.Node, error)); ok {
		return rf(ctx, id, routes)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, []string) *v1.Node); ok {
		r0 = rf(ctx, id, routes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Node)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, []string) error); ok {
		r1 = rf(ctx, id, routes)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetPolicy provides a mock function with given fields: ctx, policy
func (_m *MockHeadscaleClient) SetPolicy(ctx context.Context, policy string) error {
	ret := _m.Called(ctx, policy)

	if len(ret) == 0 {
		panic("no return value specified for SetPolicy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, policy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetTags provides a mock function with given fields: ctx, id, tags
func (_m *MockHeadscaleClient) SetTags(ctx context.Context, id uint64, tags []string) (*v1.Node, error) {
	ret := _m.Called(ctx, id, tags)

	if len(ret) == 0 {
		panic("no return value specified for SetTags")
	}

	var r0 *v1.Node
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, []string) (*v1.Node, error)); ok {
		return rf(ctx, id, tags)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, []string) *v1.Node); ok {
		r0 = rf(ctx, id, tags)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Node)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, []string) error); ok {
		r1 = rf(ctx, id, tags)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockHeadscaleClient creates a new instance of MockHeadscaleClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHeadscaleClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHeadscaleClient {
	mock := &MockHeadscaleClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
